### ISSUE TITLE
Installation on Mac OS X

### ISSUE THREAD

**Issue by odyssey4me** [directord/directord#122]
This is not exactly a bug or feature request. I am not sure where to put this into the docs, so I figure I could register this for discussion and we take it from there.

I'd like to be able to use DirectorD from a Mac OS X workstation. I thought of perhaps creating a homebrew formulae, which may be an option - but it all starts from being able to setup a virtualenv.

So far, this is working for me:

```
brew install cmake libssh2 
python3 -m venv ~/.venvs/directord
source ~/.venvs/directord/bin/activate
pip install directord
```

I've created https://github.com/odyssey4me/homebrew-directord for a homebrew package if that's of interest. Of course we could move that into this repository and have it automatically update for every release.

**Comment by cloudnull** [comment]
A homebrew formula would be fantastic and I would love to see that added to our release workflows. Anything we can do to streamline the developer experience I'm 💯 👍🏼

**Comment by cloudnull** [comment]
This was moved into https://github.com/directord/homebrew-directord, closing this issue for now.
